name: Publish

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com
          scope: '@idalovkh'
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build library
        run: npm run build

      - name: Publish packages
        run: |
          npm publish -w @idalovkh/taqseet-ui-tokens --access restricted
          npm publish -w @idalovkh/taqseet-ui-styles --access restricted
          npm publish -w @idalovkh/taqseet-ui-react --access restricted
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
